# Generated by Django 3.1.7 on 2021-02-28 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=300)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('_license', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('date_certificate_start', models.DateField(blank=True)),
                ('date_certificate_emd', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('_next', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.CharField(max_length=250)),
                ('order_file', models.FileField(blank=True, upload_to='')),
                ('_license', models.CharField(max_length=250)),
                ('_license_file', models.FileField(blank=True, upload_to='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Trials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_app.object')),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_builder', to='database_app.company')),
                ('builder_people', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_builder_people', to='database_app.people')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_customer', to='database_app.company')),
                ('customer_people', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_cust_people', to='database_app.people')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_designer', to='database_app.company')),
                ('designer_people', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_designer_people', to='database_app.people')),
                ('general_contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_contractor', to='database_app.company')),
                ('general_contractor_people', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_contractor_people', to='database_app.people')),
                ('general_contractor_tech', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_general_contractor_tech_people', to='database_app.people')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('documents', models.ManyToManyField(to='database_app.Documents')),
            ],
        ),
        migrations.CreateModel(
            name='HiddenWorksSurveyCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_signature', models.DateField()),
                ('status', models.CharField(choices=[('d', 'Черновик'), ('p', 'Распечатан'), ('w', 'Подписан')], max_length=1)),
                ('number', models.CharField(max_length=40)),
                ('other_people', models.CharField(max_length=200)),
                ('_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_app.object')),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiddenworkssurveycertificate_builder', to='database_app.company')),
                ('builder_people', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiddenworkssurveycertificate_builder_people', to='database_app.people')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiddenworkssurveycertificate_customer', to='database_app.company')),
                ('customer_people', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiddenworkssurveycertificate_cust_people', to='database_app.people')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiddenworkssurveycertificate_designer', to='database_app.company')),
                ('designer_people', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiddenworkssurveycertificate_designer_people', to='database_app.people')),
                ('general_contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiddenworkssurveycertificate_contractor', to='database_app.company')),
                ('general_contractor_people', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiddenworkssurveycertificate_contractor_people', to='database_app.people')),
                ('general_contractor_tech', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiddenworkssurveycertificate_general_contractor_tech_people', to='database_app.people')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_app.job')),
                ('material', models.ManyToManyField(to='database_app.Material')),
                ('schemas', models.ManyToManyField(to='database_app.ExecutiveScheme')),
                ('trials', models.ManyToManyField(to='database_app.Trials')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
