# Generated by Django 3.1.7 on 2021-02-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiddenworkssurveycertificate',
            name='material',
        ),
        migrations.AddField(
            model_name='hiddenworkssurveycertificate',
            name='material',
            field=models.ManyToManyField(to='database_app.Material'),
        ),
    ]
