# Generated by Django 3.1.7 on 2021-02-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0002_auto_20210223_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('date_certificate_start', models.DateField(blank=True)),
                ('date_certificate_emd', models.DateField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='material',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='material',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='material',
            name='date_certificate_emd',
        ),
        migrations.RemoveField(
            model_name='material',
            name='date_certificate_start',
        ),
        migrations.RemoveField(
            model_name='hiddenworkssurveycertificate',
            name='schemas',
        ),
        migrations.AddField(
            model_name='hiddenworkssurveycertificate',
            name='schemas',
            field=models.ManyToManyField(to='database_app.ExecutiveScheme'),
        ),
        migrations.RemoveField(
            model_name='hiddenworkssurveycertificate',
            name='trials',
        ),
        migrations.AddField(
            model_name='hiddenworkssurveycertificate',
            name='trials',
            field=models.ManyToManyField(to='database_app.Trials'),
        ),
        migrations.AddField(
            model_name='material',
            name='documents',
            field=models.ManyToManyField(to='database_app.Documents'),
        ),
    ]
